### PR TITLE
Time related additions

### PR DESCRIPTION
**Pull request by asavartsov**
Added support for millisecond resolution (aware of automatic scaling stuff) and $time/$from substitutions in dashboard variables.

### Millisecond resolution

If your data has timestamp with millisecond resolution, you can use Column:TimeStampMs type with UInt64 column as your time column.
Template variables like `$from`, `$to` or `$interval` will also have a unit of millisecond.

### Time range dependent variable values

If you wish to have your dashboard variables to depend on selected time range, you need to set such varable to refresh on time range change.
After doing this, you can use `$from` and `$to` in your queries. Notice that in this case `$from` and `$to` will always be milliseconds.

### CODE REVIEW

**Comment by hagen1778** [comment]
Hi @asavartsov 
Thank you for taking your time! It looks great! I'll review it soon.

I'm just curios what is the schema of your table with milliseconds column? I was sure that storing milliseconds will be inefficient for CH. And the only way to store such precision and do not lost performance - using multiple columns. For example, `Date` for `MergeTree`, `DateTime` for seconds and `UInt16` for milliseconds. Also, this approach is recommended here https://github.com/yandex/ClickHouse/issues/57#issuecomment-232922202

What do you think?

**Comment by asavartsov** [comment]
@hagen1778 I have a time column which contains timestamp in ms and date column for merge tree which materialized from time. As for random nature of ms data - I do not think that I have such problem in my case because my event source generates timestamps at fixed period of 20ms starting from .000, so I have always .000, .020, .040 etc millisecond value.

**Comment by daledude** [comment]
Was there a major problem with this were it needed to be closed instead of merged? We use UInt64 for timestamp for "reasons". It would be very nice to, at the very list, allow listing UInt64 fields in the selection instead of limiting to just UInt32.

**Comment by hodgesrm** [comment]
Hi @daledude, 
It appears this was closed because the requested changes were not made.  It's a large PR and it's hard if the work is not complete.  Do you want to pick up the PR and make the requested change?

I recently joined the project and will be reviewing pending work as well as PRs. I'll put this on the list for review but due to other pending tasks it may take some time to get to this one.

**Comment by thomas-pedersen** [comment]
Was this ever solved? We use Uint64 for timestamps, but can't get it to work with grafana..

**Pull request closed without merging**
