### PR TITLE
Conditional test

### PR DESCRIPTION
**Pull request by TH-HA**
Hello 
I've quickly developed this feature to remove unnecessary predicate when All is selected in combobox and when nothing is enter in textbox. 
I may extend it to additional variable type in the coming days.

To make this simple ( in term of implementation ) , i'm doing the check and query change before anything in the replace method.

Please note it's my first dev in typescript , so any remarks are more than welcome and also if you can give some guidance on how to add test on this.

For a full description of the macro, i've updated the doc under the template section

### CODE REVIEW

**Comment by hodgesrm** [comment]
Hello @TH-HA! Thanks for the PR.  I'm now working on review and will try it out over the weekend.  If it looks good I'll merge or get back with feedback.

**Comment by TH-HA** [comment]
Hello @hodgesrm  
Do you have any feedback on this PR ?
Thanks

**Comment by hodgesrm** [comment]
Hi @TH-HA!  We've been working on this behind the scenes--I'm setting up a dev environment where I can reliably test changes against different versions so that we can merge without creating regressions. That's been a bit of a puzzle since we want to be able to merge quickly but manually testing things is quite slow. 

Your code and documentation looks good at first glance but it's hard to visually identify regressions.  How did you validate this change and which version of Grafana did you use?  I'm currently working on validation against Grafana 6.1.6.  Can you add a sample dashboard that exercises this feature?  If I can load that I'll merge. 
 
Thanks!

**Comment by TH-HA** [comment]
Hello @hodgesrm 

 to validate the regression , i ve built a few dashboard using it and then using the devtools of our favorite webbrowser ( firefox/chrome ) was the main source of information.
Then the generated sql was enough to help me validate that the macro is correctly removing the condition based on the filter selection.  
I'm currently using grafana 6.1.4 , but i need to try it on a 5.X.

Do you have any pointer on how test are written in the plugin , i can add a few and also use the existing one to do non regression testing also on my side. 

I'll add some example dashboard in the branch to show how it works ( I'll try to make those dashboard working on the CH system table , like this they won't require any specific schema - And also it can be the start of some usefull/fancy monitoring dashboard working out of the box with CH without any additional third party neither additional storage as you need to use prometheus ....).
I'll add them before the end of the week in the branch. 

I 'll take the opportunity of this interaction to ask you some feedback on the naming : 
  today it's conditionalTest for the macro.
  We can use something more explicit : conditionalSQL 
  We can also extend it to text box variables ( especially since the latest evolution of CH contain a lot of feature related to text analysis - multi search / fuzzysearch / ngram ) with some intelligence ( remove the predicate if the value is null or .* for regexp for instance ).  
   

Regards

**Comment by admitad-github** [comment]
Hello, any progress on this issue? Really looking forward to use this feature, it's a real game-changer for some filter-heavy dashboards 👍

**Comment by gimm3fuel** [comment]
Hello @TH-HA!

We've made another look at this request and here are some notes before we can merge it:
1. It does have unrelated changes of namespace handling for imports. I believe it should not be a part of this pr.
2. It removes the identifier escaping logic which is crutial for the plugin. Could you please revert it back?

Thanks, Andrey

**Comment by TH-HA** [comment]
I'll update the code to include the escaping logic in the function. I hope to be able to submit it next week. 
On the first part , can you be more specific ? i didn't change the namespace in import ( at least not on purpose ).  
Regards

**Comment by gimm3fuel** [comment]
> On the first part , can you be more specific ? i didn't change the namespace in import ( at least not on purpose ).

There was a piece of code that imported a cetain functions from 'lodash-es' lib: 

`import {each, isArray, isEmpty, isString, map} from 'lodash-es';`

In your PR it has been changed to: 

`import _ from 'lodash';`

So the function calls have been changed from i.e. `isEmpty(somthing)` to `_.isEmpty(something)`. If you didn't do that on purpose perhaps your IDE did.

**Comment by TH-HA** [comment]
ok , i've changed everything as discussed. I 'll test tomorrow morning.

Regards

**Comment by gimm3fuel** [comment]
Hi @TH-HA,

All looks correct now! Thanks! We are going to merge it today. There is a small typo in documentation: `$condionalTest` instead of `$conditionalTest`. If it's not much trouble for you, could you please make a quick fix of it.

**Comment by TH-HA** [comment]
sorry for that , it's fixed

**Pull request merged**
