### PR TITLE
[PROPOSITION] Support custom labels for $columns expression

### PR DESCRIPTION
**Pull request by asavartsov**
I've added support for custom labels in `$columns`. User need to specify a string (in single quotes) as `key` argument. All tokens starting with `%` will be passed to `SELECT`, `GROUP BY` and `ORDER BY` blocks and key will be transformed to a `concat` expression. 

Example:

```
$columns('TEC %sat %primaryfreq-%secondaryfreq', avg(tec) tec) FROM $table WHERE sat IN ($sat)
```

Generated SQL:

```
SELECT 
  t, 
  groupArray((concat('TEC', sat, ' ', primaryfreq, '-', secondaryfreq), tec)) as groupArr 
FROM ( 
  SELECT 
    intDiv(time, 5000) * 5000 as t, 
    sat, 
    primaryfreq, 
    secondaryfreq, 
    avg(tec) tec 
  FROM 
    rawdata.ismrawtec 
  WHERE 
    d BETWEEN toDate(1522398655340/1000) AND toDate(1522403072252/1000) AND time BETWEEN 1522398655340 AND 1522403072252 AND  sat IN ('GPS5','GLONASS6','GPS7','GLONASS7','GPS8')
  GROUP BY 
    t, sat, primaryfreq, secondaryfreq  
  ORDER BY 
    t, sat, primaryfreq, secondaryfreq
) 
GROUP BY t 
ORDER BY t
```

Result:

image

### CODE REVIEW

**Comment by hagen1778** [comment]
Hi @asavartsov 
Looks very nice! Thank you for improving the plugin!

I was trying to build a similar query with `concat` in `$columns`:
```
$columns(
    concat('TEC', sat, ' ', primaryfreq, '-', secondaryfreq) key,
    avg(tec) tec)
FROM $table
WHERE sat IN ($sat)
```

The query above will work too, as far as I understand your proposal. But when I tried to use it on my test table I realized that some of my columns are not `string` and must be converted. And without templating it's clear what I need to do to convert the column:
` concat('TEC', sat, ' ', toString(primaryfreq), '-', secondaryfreq) key,`
Will it work the same way if we'll use custom labels?
Another thing is support of `rate` macros, because it has the similar interface for user and he will try to apply custom labels there also.

**Comment by asavartsov** [comment]
@hagen1778 Thanks for answer! The main idea was to hide that `concat` clutter from user, I just was more explicit in select/group by. If it's OK to group by concatenated string instead of list of columns, generated SQL could be simplified. 

You're right about non-string columns, I missed that case. It's probably safe to just `toSting`ing everything.

`$rateColums` works just as expected with this code.

**Comment by asavartsov** [comment]
Actually, this was inspired by OpenTSDB plugin which I was using before CH: it allows you to use $tag_ expression in Alias field (like TEC $tag_sat).

I have to used to pattern of one metric - one query, which works for a great amount of cases. This scenario could be easily implemented with OpenTSDB-plugin-like GUI to generate colums/rateColums expression leaving raw SQL code option only for non-trivial scenarios (personally, I'd better create a view which exposes values I need instead)

**Comment by hagen1778** [comment]
>  If it's OK to group by concatenated string instead of list of columns, generated SQL could be simplified.

Frankly, I don't see big difference in performance between these cases. Please, let me know if it exist.
This PR can't be merged without some changes connected with type casting. Also, did you tried it with `$rate` macros?

**Comment by hagen1778** [comment]
Closed due to inactivity

**Pull request closed without merging**
