### PR TITLE
Replace query with evalQuery

### PR DESCRIPTION
**Pull request by a-venger**
After discussion on https://github.com/Vertamedia/clickhouse-grafana/pull/389 I realized that there is no need to have separate logic for Unified and Legacy alerting.

1. RawQuery is not required in alerting
2. Interval was set to int while it was still string in Unified alerting. And setting interval during alert creation will break it in Unified alerting.

image

### CODE REVIEW

**Comment by Slach** [comment]
Did you test your changes with graph panel based old alerts?

**Comment by a-venger** [comment]
> Did you test your changes with graph panel based old alerts?

yes
Seems good

**Comment by Slach** [comment]
> > Did you test your changes with graph panel based old alerts?
> yes Seems good

Even with template variables and adhoc after press "save dashboard"?

**Comment by a-venger** [comment]
> > > Did you test your changes with graph panel based old alerts?
> > > yes Seems good
> 
> Even with template variables and adhoc after press "save dashboard"?

I see your point. 
Nope without variables. 
But I am not expecting that plugin will support variables as it is for multiple others datasources.

I can understand that it was "working" with rawQuery

Feel free to close this PR if you think that variables support with rawQuery is required.

**Comment by Slach** [comment]
@a-venger sorry, I really appreciated your efforts, but need close PR.

I agree with you. Current support variables and `adhoc` filters look weird, but it was a side effect of bad design decisions of Grafana itself when they attach alerts into graph panel instead of create separate alerts from begin.

I just care about 2.3.1 users which use plugin now and after apply your changes their dashboard alerts will just not work. 
And we will see the lot of issues here without solution even we will describe in documentation about plugin incompatibility.

Currently, I prepare 2.4.1 where I will fix annoyed you warning message.

Maybe you have enough frontend experience to help me resolve some security issues https://github.com/Vertamedia/clickhouse-grafana/security/dependabot?

**Pull request closed without merging**
