### PR TITLE
fix: clickhouse syntax highlight not working

### PR DESCRIPTION
**Pull request by songjiao**
fix clickhouse syntax highlight not working

### CODE REVIEW

**Comment by Slach** [comment]
Hello @songjiao, sorry for so long response time 
I promise, from current moment we will spend more time and give more quickly community feedback 

could you try to resolve conflicts with the latest version and add a screenshot in Readme which explained how to syntax highlight working in your branch with complex queries contains macros etc.

Also, could you check with docker-compose compatibility with Grafana 7 with current docker-compose development environment?

**Comment by zifter** [comment]
@songjiao @Slach Any updates for this pr?

**Comment by Slach** [comment]
@zifter feel free to make new PR with the same fixes
I not sure this fixes works well on latest Grafana 7.x

could you try to test it?

```
wget  https://github.com/songjiao/clickhouse-grafana/archive/refs/heads/fix-clickhouse-highlight-not-working.zip
unzip fix-clickhouse-highlight-not-working.zip
cd fix-clickhouse-highlight-not-working
npm run build:prod
cd ../

git clone https://github.com/Vertamedia/clickhouse-grafana.git
cp -fv fix-clickhouse-highlight-not-working/dist ./clickhouse-grafana/dist

cd clickhouse-grafana
touch .env 
```

register on grafana.com
goto MyAccount -> plugins
create plugin
and make API KEY for it

create `clickhouse-grafana/.env` file with following content
```
GRAFANA_API_KEY=<API_KEY_FROM_grafana.com->My account>
```

run
```
docker-compose run plugin_signer
docker-compose up -d grafana
```

open http://localhost:3000/ -> Dashboards -> manage
and try to open any clickhouse related dashboard

**Comment by Slach** [comment]
@zifter did you try to check functionality?

**Comment by Slach** [comment]
@songjiao thanks a lot for your efforts, I need to close PR due to inactivity, look like the latest `master` resolves issue with syntax highlight

**Pull request closed without merging**
