### PR TITLE
Remove $dateCol and add $timeFilterColumn

### PR DESCRIPTION
**Pull request by simPod**
## New Features

* add `$timeFilterColumn(columnname)` macro. Allows to use filters in Query variables.

## Dropped

* `$dateCol` is no longer used as is not required by ClickHouse anymore. Resolves [#48](https://github.com/Vertamedia/clickhouse-grafana/issues/48)

### CODE REVIEW

**Comment by hagen1778** [comment]
Hi @simPod 

I'm not sure that dropping `$dateCol` is necessary. There could be a lot of users with "old" massive tables and `Date` column for partitioning. Ignoring `Date` column in filters could decrease performance significantly. According to #48 `$dateCol` don't have to be required anymore, but it could be optional. Doing so we need to make `$timeFilter` know which time-related columns were set and build conditions accordingly.

I suggest following:
* make fields `Date` and `DateTime` optional in `queryBuilder`
* at least one time-related column must be set
* $timeFilter must consider previously set time-related fields.

What do you think?

**Comment by simPod** [comment]
@hagen1778 I can see what I can do. Do you mean it decreases performance only for those old tables (old version of clickhouse), right?

**Comment by hagen1778** [comment]
I mean, there are cases where column `Date` is still relevant and is in the primary key expression. In Vertamedia, for example. We must filter queries by `Date` if we want to speed them up. The point is in having following options in timeFilter: 
* using `Date`
* using `DateTime` 
* using `Date` and `DateTime`

**Comment by simPod** [comment]
@hagen1778 can you point me how you would approach

> make fields Date and DateTime optional in queryBuilder
> at least one time-related column must be set

?

I made those optional in query generation code

**Comment by hagen1778** [comment]
Please, see https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.8.0

**Comment by simPod** [comment]
@hagen1778 thanks, just got to it. 

How can I do something similar like I could with this PR `$timeFilterColumn(column_name)`? Or should I rework it to new PR? Havent't find a way to do so.

Let's consider I use it in variable query as well. Thanks

**Pull request closed without merging**
